Flippa={};Flippa.Utils={};Flippa.Forms={};Flippa.User=function(id)
{this.id=id||null;var self=this;this.fetchFromHeader=function(){var profile_link=$('ul.login-register a.profile');var userid=profile_link.data('userid');if(userid==undefined){return null;}
userid=parseInt(userid);if(isNaN(userid)){return null;}
else{this.id=userid;this.name=$('ul.login-register a.profile').data('username');return self;}};return this;}
Flippa.ObjectStore=function(key){try{localStorage.setItem('test',1);localStorage.removeItem('test');}catch(e){return{exists:function(){return false},get:function(key){return null},getAll:function(key){return null},set:function(key,value){},setAll:function(obj){},save:function(){return false},refresh:function(){},destroy:function(){}}}
var self=this;this.key=key;this.refresh=function(){var tmp_data=localStorage.getItem(key);self.data=(tmp_data&&JSON.parse(tmp_data))||{};};this.save=function(){try{localStorage.setItem(self.key,JSON.stringify(self.data));return true;}
catch(e){return false;}};this.get=function(key){return key in self.data?self.data[key]:undefined;};this.set=function(key,value){self.data[key]=value;self.save();};this.getAll=function(){return self.data;};this.setAll=function(obj){self.data=obj;self.save();};this.destroy=function(){localStorage.removeItem(self.key);};this.exists=function(){return localStorage.getItem(self.key)!==null;};this.refresh();return this;}
Flippa.Utils.formatNumber=function(number,decimals,dec_point,thousands_sep)
{var n=!isFinite(+number)?0:+number,prec=!isFinite(+decimals)?0:Math.abs(decimals),sep=(typeof thousands_sep==='undefined')?',':thousands_sep,dec=(typeof dec_point==='undefined')?'.':dec_point,s='',toFixedFix=function(n,prec){var k=Math.pow(10,prec);return''+Math.round(n*k)/k;};s=(prec?toFixedFix(n,prec):''+Math.round(n)).split('.');if(s[0].length>3){s[0]=s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,sep);}
if((s[1]||'').length<prec){s[1]=s[1]||'';s[1]+=new Array(prec-s[1].length+1).join('0');}
return s.join(dec);}
Flippa.Forms.makeDependantOnCheckbox=function(elemId,checkboxId)
{var elem=$('#'+elemId);var check=$('#'+checkboxId);check.change(function(){if(check.is(':checked'))
{elem.removeAttr('disabled');elem.parent().parent('div.fieldrow').removeClass('disabled');}
else
{elem.attr('disabled','disabled');elem.parent().parent('div.fieldrow').addClass('disabled');}});};Flippa.Forms.MaximumCharacterField=function(){var self=this;self.field=null;self.counter_message=null;self.character_limit=0;self.init=function(config){self.field=$("#"+config.id);if(self.field.next("span.length-counter").length){return;}
self.character_limit=config.limit||250;self.counter_message=$(document.createElement("span"));self.counter_message.attr("class","length-counter");self.update_counter();self.field.after(self.counter_message);self.field.on("keyup",self.update_counter);};self.update_counter=function(){var remaining=self.character_limit-self.field.val().length;if(remaining<0){self.counter_message.text(self.character_limit+" character limit exceeded");self.counter_message.addClass("error");}
else{self.counter_message.text(remaining+" characters remaining");self.counter_message.removeClass("error");}};};Date.prototype.toRelativeTime=function(now_threshold){var delta=this.delta();now_threshold=parseInt(now_threshold,10);var days=86400000;if(isNaN(now_threshold)){now_threshold=5000;}
if(Math.abs(delta)<=now_threshold){return'Just now';}else if(delta>1*days&&delta<2*days){return'Yesterday';}
var units=null;var conversions={millisecond:1,second:1000,minute:60,hour:60,day:24,month:30,year:12};for(var key in conversions){if(Math.abs(delta)<conversions[key]){break;}else{units=key;delta=delta/conversions[key];}}
delta=delta>0?Math.floor(delta):Math.ceil(delta);if(Math.abs(delta)!==1){units+="s";}
return delta>0?[Math.abs(delta),units,"ago"].join(" "):[Math.abs(delta),units].join(" ");};Date.prototype.delta=function(){return new Date()-this;};Date.prototype.toLocalTimeString=function(){hours=this.getHours();minutes=this.getMinutes();period="am";if(hours>=12){period="pm";hours-=12;}
timeString=[hours>0?hours:12,":",minutes,period].join("");return[this.toDateString(),timeString].join(" ");};Date.fromString=function(str){return new Date(Date.parse(str));};Flippa.Utils.processLiveTimes=function(element){context=element||'#content'
$('.sitepoint-datetime',$(context)).each(function(){var self=this;var dateString=$(self).text();$(self).attr('title',dateString);var update=function(){var date=Date.fromString($(self).attr('title'));var delta=date.delta();var hours=3600000;$(self).text(date.toRelativeTime());if(delta>-1*hours&&delta<0){$(self).addClass('imminent');}else{$(self).removeClass('imminent');}};update();window.setInterval(update,1000);});};$(document).ready(function(){Flippa.Utils.processLiveTimes();});Flippa.SiteAlerts=new function(){this.hideAlert=function(e){e.preventDefault();var hiddenIds=[];var k=$(this).data('alertkey');var cookieBits=document.cookie.split(/\s*;\s*/g);for(var i in cookieBits)
{var nvp=cookieBits[i].split('=');var key=unescape(nvp[0]);var value=unescape(nvp[1]);if(key=="hidden_alerts")
{hiddenIds=value.split(':');}}
hiddenIds.push(k);var date=new Date();date.setTime(date.getTime()+(999*24*60*60*1000));document.cookie="hidden_alerts="+hiddenIds.join(':')+"; expires="+date.toGMTString()+"; path=/"+"; domain="+COOKIE_DOMAIN;$("#site_alert_"+k).remove();var alertRow=document.getElementById('site_alert_'+k);var alertList=document.getElementById('notice-bar');if(alertList&&!alertList.getElementsByTagName('p').length)
{$(alertList).hide('fast');}}};$("a[rel~=external]").attr("target","_blank");$(".description a[rel~=nofollow]").attr("target","_blank");(function($){$.fn.hoverIntent=function(f,g){var cfg={sensitivity:7,interval:100,timeout:0};cfg=$.extend(cfg,g?{over:f,out:g}:f);var cX,cY,pX,pY;var track=function(ev){cX=ev.pageX;cY=ev.pageY;};var compare=function(ev,ob){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t);if((Math.abs(pX-cX)+Math.abs(pY-cY))<cfg.sensitivity){$(ob).unbind("mousemove",track);ob.hoverIntent_s=1;return cfg.over.apply(ob,[ev]);}else{pX=cX;pY=cY;ob.hoverIntent_t=setTimeout(function(){compare(ev,ob);},cfg.interval);}};var delay=function(ev,ob){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t);ob.hoverIntent_s=0;return cfg.out.apply(ob,[ev]);};var handleHover=function(e){var p=(e.type=="mouseover"?e.fromElement:e.toElement)||e.relatedTarget;while(p&&p!=this){try{p=p.parentNode;}catch(e){p=this;}}if(p==this){return false;}var ev=jQuery.extend({},e);var ob=this;if(ob.hoverIntent_t){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t);}if(e.type=="mouseover"){pX=ev.pageX;pY=ev.pageY;$(ob).bind("mousemove",track);if(ob.hoverIntent_s!=1){ob.hoverIntent_t=setTimeout(function(){compare(ev,ob);},cfg.interval);}}else{$(ob).unbind("mousemove",track);if(ob.hoverIntent_s==1){ob.hoverIntent_t=setTimeout(function(){delay(ev,ob);},cfg.timeout);}}};return this.mouseover(handleHover).mouseout(handleHover);};})(jQuery);$(function(){$(".nav li.parent>a").click(function(){return false;});$(".nav li").hoverIntent(function(){$(this).addClass("hover");$('ul:first',this).css('visibility','visible');},function(){$(this).removeClass("hover");$('ul:first',this).css('visibility','hidden');});});